// <auto-generated />
namespace Point_of_Sales.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class posV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(posV1));
        
        string IMigrationMetadata.Id
        {
            get { return "202207121206117_posV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
